name: deploy on coolify

on:
  workflow_dispatch:
  push:
    tags:
    - '**'

jobs:
  build-and-deploy:
    runs-on: node:lts
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Test
        run : npm run test
      
      - name: Build
        run : npm run build

      # - name: Deploy to Coolify
      #   run: | 
      #    [ $(curl --request GET 'https://coolify.sandbox.app-deploy.xyz/api/v1/deploy?uuid=${{ vars.COOLIFY_APP_ID }}&force=false' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}' -o /dev/stderr -w "%{http_code}") -eq 200 ]
